name: Build

on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    container: 
      image: mcr.microsoft.com/dotnet/nightly/sdk:8.0

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Make build.sh executable
      run: chmod +x ./build.sh

    - name: Run build.sh
      run: ./build.sh