name: Build

on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]


    container: 
      image: mcr.microsoft.com/dotnet/nightly/sdk:8.0

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Make build.sh executable (Unix)
      if: runner.os != 'Windows'
      run: chmod +x ./build.sh

    - name: Run build.sh on Unix
      if: runner.os != 'Windows'
      run: ./build.sh $SSHKey
    
    - name: Run build.cmd on Windows
      if: runner.os == 'Windows'
      run: .\build.cmd

    